import '@styles/globals.css'
import Provider from "@components/Provider";
import Navbar from '@components/Navbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
      <Provider>
      <div className='main'>
          <div className='gradient' />
          </div>
          <main className="app">
          <Navbar />
          {children}
        </main>
      </Provider>
       </body>
    </html>
  )
}
